name: Diffy Integration
on: 
  workflow_dispatch:

jobs:
  diffy_integration:
    runs-on: ubuntu-latest
    name: Diffy Integration
    steps:
      - uses: actions/checkout@v2
      - name: Diffy
        run: |
          chmod +x ./.github/workflows/diffy/screenshot-deploy-screenshot-diff.sh
          ./.github/workflows/diffy/screenshot-deploy-screenshot-diff.sh
        shell: bash
        env:
          DIFFY_API_KEY: ${{ secrets.DIFFY_API_KEY }}
          DIFFY_PROJECT_ID: ${{ secrets.DIFFY_PROJECT_ID }}
          DIFFY_ENV1: prod
          DIFFY_ENV2: stage
